// ============================================
//  УНИВЕРСАЛЬНЫЙ КОНФИГ СИМВОЛОВ
//  Все параметры монет, которые использует бот
// ============================================

const fs = require('fs');
const path = require('path');

// Базовый конфиг для самых популярных монет
const FALLBACK_CONFIG = {
  'SOL-USDT': { precision: 3, minQty: 0.01 },
  'XRP-USDT': { precision: 3, minQty: 0.01 },
  'ETH-USDT': { precision: 3, minQty: 0.001 },
  'BTC-USDT': { precision: 3, minQty: 0.001 },
  'BNB-USDT': { precision: 3, minQty: 0.01 },
  'ADA-USDT': { precision: 2, minQty: 1 },
  'DOGE-USDT': { precision: 2, minQty: 1 },
  'DOT-USDT': { precision: 2, minQty: 0.1 },
  'LTC-USDT': { precision: 2, minQty: 0.01 },
  'LINK-USDT': { precision: 2, minQty: 0.01 },
  'UNI-USDT': { precision: 2, minQty: 0.01 },
  'ATOM-USDT': { precision: 2, minQty: 0.01 },
  'AVAX-USDT': { precision: 2, minQty: 0.01 },
  'MATIC-USDT': { precision: 2, minQty: 1 },
  'NEAR-USDT': { precision: 2, minQty: 0.01 },
  'FIL-USDT': { precision: 2, minQty: 0.01 },
  'AAVE-USDT': { precision: 2, minQty: 0.01 },
  'VET-USDT': { precision: 2, minQty: 1 },
  'TRX-USDT': { precision: 2, minQty: 1 },
  'XLM-USDT': { precision: 2, minQty: 1 },
  'ALGO-USDT': { precision: 2, minQty: 1 },
  'EGLD-USDT': { precision: 2, minQty: 0.01 },
  'HBAR-USDT': { precision: 2, minQty: 1 },
  'KAVA-USDT': { precision: 2, minQty: 0.1 },
  'KSM-USDT': { precision: 2, minQty: 0.01 },
  'MKR-USDT': { precision: 2, minQty: 0.001 },
  'ZEC-USDT': { precision: 2, minQty: 0.01 },
  'XMR-USDT': { precision: 2, minQty: 0.01 },
  'DASH-USDT': { precision: 2, minQty: 0.01 },
  'YFI-USDT': { precision: 2, minQty: 0.001 },
  'COMP-USDT': { precision: 2, minQty: 0.01 },
  'GRT-USDT': { precision: 2, minQty: 1 },
  'SNX-USDT': { precision: 2, minQty: 0.1 },
  'CRV-USDT': { precision: 2, minQty: 1 },
  '1INCH-USDT': { precision: 2, minQty: 1 },
  'ENJ-USDT': { precision: 2, minQty: 1 },
  'MANA-USDT': { precision: 2, minQty: 1 },
  'SAND-USDT': { precision: 2, minQty: 1 },
  'AXS-USDT': { precision: 2, minQty: 0.01 },
  'GALA-USDT': { precision: 2, minQty: 1 },
  'APE-USDT': { precision: 2, minQty: 0.01 },
  'OP-USDT': { precision: 2, minQty: 0.01 },
  'ARB-USDT': { precision: 2, minQty: 0.01 },
  'INJ-USDT': { precision: 2, minQty: 0.01 },
  'SEI-USDT': { precision: 2, minQty: 0.01 },
  'SUI-USDT': { precision: 2, minQty: 0.01 },
  'APT-USDT': { precision: 2, minQty: 0.01 },
  'LDO-USDT': { precision: 2, minQty: 0.01 },
  'RUNE-USDT': { precision: 2, minQty: 0.01 },
  'FLOW-USDT': { precision: 2, minQty: 0.01 },
  'STX-USDT': { precision: 2, minQty: 0.01 },
  'AR-USDT': { precision: 2, minQty: 0.01 },
  'ENS-USDT': { precision: 2, minQty: 0.01 },
  'BAT-USDT': { precision: 1, minQty: 23.6 },
  'STORJ-USDT': { precision: 2, minQty: 0.1 },
  'IMX-USDT': { precision: 2, minQty: 0.01 },
  'ZRX-USDT': { precision: 2, minQty: 1 },
  'SKL-USDT': { precision: 2, minQty: 1 },
  'SUSHI-USDT': { precision: 2, minQty: 0.1 },
  'YGG-USDT': { precision: 2, minQty: 0.01 },
  'RSR-USDT': { precision: 2, minQty: 1 },
  'KNC-USDT': { precision: 2, minQty: 0.1 },
  'GMT-USDT': { precision: 2, minQty: 0.01 },
  'ROSE-USDT': { precision: 2, minQty: 1 },
  'MINA-USDT': { precision: 2, minQty: 0.01 },
  'CFX-USDT': { precision: 0, minQty: 48 },
  'API3-USDT': { precision: 2, minQty: 0.01 },
  'AGLD-USDT': { precision: 2, minQty: 0.01 },
  'SLP-USDT': { precision: 2, minQty: 1 },
  'JASMY-USDT': { precision: 2, minQty: 1 },
  'CTK-USDT': { precision: 2, minQty: 0.01 },
  'MTL-USDT': { precision: 2, minQty: 0.01 },
  'PEOPLE-USDT': { precision: 2, minQty: 1 },
  'ANKR-USDT': { precision: 2, minQty: 1 },
  'WOO-USDT': { precision: 2, minQty: 0.01 },
  'CRO-USDT': { precision: 2, minQty: 1 },
  'LUNC-USDT': { precision: 2, minQty: 1 },
  'LUNA-USDT': { precision: 2, minQty: 0.01 },
  'QNT-USDT': { precision: 2, minQty: 0.01 },
  'ARPA-USDT': { precision: 2, minQty: 1 },
  'SFP-USDT': { precision: 2, minQty: 0.01 },
  'MAGIC-USDT': { precision: 2, minQty: 0.01 },
  'FET-USDT': { precision: 2, minQty: 0.01 },
  'GMX-USDT': { precision: 2, minQty: 0.01 },
  'COTI-USDT': { precision: 2, minQty: 0.01 },
  'METIS-USDT': { precision: 2, minQty: 0.01 },
  'ASTR-USDT': { precision: 2, minQty: 0.01 },
  'DUSK-USDT': { precision: 2, minQty: 0.01 },
  'BLUR-USDT': { precision: 2, minQty: 1 },
  'ACH-USDT': { precision: 2, minQty: 1 },
  'TRB-USDT': { precision: 2, minQty: 0.01 },
  'FLOKI-USDT': { precision: 2, minQty: 1 },
  'ILV-USDT': { precision: 2, minQty: 0.01 },
  'ZEN-USDT': { precision: 2, minQty: 0.01 },
  'SCRT-USDT': { precision: 2, minQty: 0.01 },
  'RLC-USDT': { precision: 2, minQty: 0.01 },
  'LPT-USDT': { precision: 2, minQty: 0.01 },
  'CKB-USDT': { precision: 2, minQty: 1 },
  'QTUM-USDT': { precision: 2, minQty: 0.01 },
  'SUN-USDT': { precision: 2, minQty: 1 },
  'IOTA-USDT': { precision: 2, minQty: 1 },
  'SSV-USDT': { precision: 2, minQty: 0.01 },
  'BICO-USDT': { precision: 2, minQty: 0.01 },
  'TLM-USDT': { precision: 2, minQty: 1 },
  'XCN-USDT': { precision: 2, minQty: 1 },
  'TWT-USDT': { precision: 2, minQty: 0.01 },
  'LQTY-USDT': { precision: 2, minQty: 0.01 },
  'ID-USDT': { precision: 2, minQty: 0.01 },
  'EDU-USDT': { precision: 2, minQty: 0.01 },
  'TURBO-USDT': { precision: 2, minQty: 1 },
  'ORDI-USDT': { precision: 2, minQty: 0.01 },
  'UMA-USDT': { precision: 2, minQty: 0.01 },
  'OKB-USDT': { precision: 2, minQty: 0.01 },
  'NMR-USDT': { precision: 2, minQty: 0.01 },
  'MAV-USDT': { precision: 2, minQty: 0.01 },
  'WLD-USDT': { precision: 2, minQty: 0.01 },
  'PENDLE-USDT': { precision: 2, minQty: 0.01 },
  'ARKM-USDT': { precision: 2, minQty: 0.01 },
  'CYBER-USDT': { precision: 2, minQty: 0.01 },
  '1000PEPE-USDT': { precision: 2, minQty: 1 },
  'KAS-USDT': { precision: 0, minQty: 68 },
  'Q-USDT': { precision: 0, minQty: 101 },
  'ORDER-USDT': { precision: 2, minQty: 59.37 },
  'FLUX-USDT': { precision: 2, minQty: 0.01 },
  'SYN-USDT': { precision: 2, minQty: 0.01 },
  'WIF-USDT': { precision: 2, minQty: 0.01 },
  'PI-USDT': { precision: 3, minQty: 0.01 },
  'FLOCK-USDT': { precision: 3, minQty: 0.01 },
  'HOLO-USDT': { precision: 2, minQty: 1 },
  'TRUST-USDT': { precision: 2, minQty: 1 },
  'BAS-USDT': { precision: 2, minQty: 1 },
  'JCT-USDT': { precision: 2, minQty: 1 },
  'NCSKAMC2USD-USDT': { precision: 3, minQty: 0.01 },
  'WLFI-USDT': { precision: 3, minQty: 0.01 },
};

/**
 * Получить параметры символа
 * @param {string} symbol - Символ (например, 'SOL-USDT')
 * @returns {Object} { precision, minQty, pricePrecision, size }
 */
function getSymbolConfig(symbol) {
  const normalized = symbol.replace(/_/g, '-');
  const config = FALLBACK_CONFIG[normalized];
  if (config) {
    return config;
  }
  console.warn(`⚠️ Символ ${symbol} не найден в конфиге, используем значения по умолчанию (precision: 3, minQty: 0.01)`);
  return { precision: 3, minQty: 0.01 };
}

module.exports = {
  getSymbolConfig,
  FALLBACK_CONFIG,
};